### ISSUE TITLE
Drama machine broke

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [Gaelan/MCDrama#31]
![image](https://user-images.githubusercontent.com/5446387/33212893-4efb3316-d125-11e7-89a8-00cb87be9737.png)

**Comment by antoinegag** [comment]
🅱rama 🅱achine 🅱roke

**Comment by Gaelan** [comment]
Yep, I'm out of Heroku hours. Will be back up at the end of the month unless someone wants to throw money at me.

**Comment by TehNut** [comment]
*tosses penny*

**Comment by Gaelan** [comment]
Bah
