### ISSUE TITLE
"An interaction between JourneyMap and JourneyMap"

### ISSUE THREAD

**Issue by JBYoshi** [Gaelan/MCDrama#46]
The generator appears to be providing duplicate values in certain cases, which can make for some weird results.

http://ftb-drama.herokuapp.com/4beaa6/8jou9dar6rjoikuwkhib1co7g

> an interaction between JourneyMap and JourneyMap causes closed source code. in an unrelated incident, techbrew refuses to add config to TheCakeMod for immersive Stealing. techbrew loses a lot of twitter followers

**Comment by Gaelan** [comment]
Hmm. It could be fixed, but it seems like quite a bit of effort for to resolve a mildly amusing bug. The non-sensical drama is part of the charm, IMO.
